Fix Room Description AttributeError: 'str' object has no attribute 'get' (#29)
* change local _LOGGER to LOGGER and shared.py optimized parsed zone clean tested for rand.

Signed-off-by: Sandro Cantarella <sandro@Sandros-Mac-mini.fritz.box>

* typing and other parser touches.

Signed-off-by: Sandro Cantarella <sandro@Sandros-Mac-mini.fritz.box>

* bump mvcrender and change the async to sync usage.

Signed-off-by: Sandro Cantarella <sandro@Sandros-Mac-mini.fritz.box>

* bump mvcrender isort and ruff and replace blending and some drawing function with C based from mcvrender.

Signed-off-by: Sandro Cantarella <sandro@509dc541-f930-4e46-87da-4482e9d9a7bb.fritz.box>

* corrections done

Signed-off-by: Sandro Cantarella <sandro@13de464c-e6f5-4665-b8d7-d6acf4207b24.fritz.box>

* corrections duplicate logger

Signed-off-by: Sandro Cantarella <sandro@13de464c-e6f5-4665-b8d7-d6acf4207b24.fritz.box>

* removing unused code.

Signed-off-by: Sandro Cantarella <sandro@Sandros-Mac-mini.fritz.box>

* delete auto_crop.py and color_utils.py as not used anymore

Signed-off-by: Sandro Cantarella <sandro@Sandros-Mac-mini.fritz.box>

* ruff formatted and some mod on drawable.py

Signed-off-by: Sandro Cantarella <sandro@03829bc9-740a-4ae1-9848-e7d8baa7c8ba.fritz.box>

* changes

Signed-off-by: Sandro Cantarella <sandro@e12ecfb7-0503-4719-87b7-0b014abdffa8.fritz.box>

* remove duplicate

* remove potential memory leak from code.

* drawable.py use now mcvrender for the most.

* version bump

Signed-off-by: Sandro Cantarella <sandro@Sandros-Mac-mini.fritz.box>

* test new battery state and add streaming to the data

Signed-off-by: Sandro Cantarella <sandro@cabf9afe-642b-4ef6-b6d4-34d9c877830b.fritz.box>

* charging state updated

Signed-off-by: Sandro Cantarella <sandro@cabf9afe-642b-4ef6-b6d4-34d9c877830b.fritz.box>

* added need room_names in RoomStore

Signed-off-by: Sandro Cantarella <sandro@1b7a9c0c-b720-40e5-a6c3-7b3a28793b2e.fritz.box>

* status_text.py refactor removing if elif else for clarity

Signed-off-by: Sandro Cantarella <sandro@Sandros-Mac-mini.fritz.box>

* adding const.py and update types.py to separate const and types

Signed-off-by: Sandro Cantarella <sandro@Sandros-Mac-mini.fritz.box>

* map_data.py handle the Rand256 crash when no Segments ID are not available

Signed-off-by: Sandro Cantarella <sandro@Sandros-Mac-mini.fritz.box>

* status_text.py

Signed-off-by: Sandro Cantarella <sandro@Sandros-Mac-mini.fritz.box>

* const.py

Signed-off-by: Sandro Cantarella <sandro@Sandros-Mac-mini.fritz.box>

* map_data.py

Signed-off-by: Sandro Cantarella <sandro@Sandros-Mac-mini.fritz.box>

* pylinted code and ruff fix stability of room data

Signed-off-by: Sandro Cantarella <sandro@Sandros-Mac-mini.fritz.box>

* last files for 12 isort / ruff and lint

Signed-off-by: Sandro Cantarella <sandro@79f3d049-9006-400d-9954-2e5dcd250fa9.fritz.box>

* adding fallback to the RoomManger class for Rooms Default Values that is added to const.py and __init__.py.

Signed-off-by: Sandro Cantarella <sandro@Sandros-Mac-mini.fritz.box>

* Remove duplicated const import

* Update version to v0.1.13 and type hint floors_trims

* Update version number to 0.1.13 remove duplicate const import

* Update version and add default rooms to parser

Bump version from 0.1.12 to 0.1.13 and add default rooms.

---------

Signed-off-by: Sandro Cantarella <sandro@Sandros-Mac-mini.fritz.box>
Signed-off-by: Sandro Cantarella <sandro@509dc541-f930-4e46-87da-4482e9d9a7bb.fritz.box>
Signed-off-by: Sandro Cantarella <sandro@13de464c-e6f5-4665-b8d7-d6acf4207b24.fritz.box>
Signed-off-by: Sandro Cantarella <sandro@03829bc9-740a-4ae1-9848-e7d8baa7c8ba.fritz.box>
Signed-off-by: Sandro Cantarella <sandro@e12ecfb7-0503-4719-87b7-0b014abdffa8.fritz.box>
Signed-off-by: Sandro Cantarella <sandro@cabf9afe-642b-4ef6-b6d4-34d9c877830b.fritz.box>
Signed-off-by: Sandro Cantarella <sandro@1b7a9c0c-b720-40e5-a6c3-7b3a28793b2e.fritz.box>
Signed-off-by: Sandro Cantarella <sandro@79f3d049-9006-400d-9954-2e5dcd250fa9.fritz.box>
Co-authored-by: Sandro Cantarella <sandro@13de464c-e6f5-4665-b8d7-d6acf4207b24.fritz.box>